NodeOUs:
  Enable: false
  ClientOUIdentifier:
    Certificate: cacerts/ca.banks.cecbs.et-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.banks.cecbs.et-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.banks.cecbs.et-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.banks.cecbs.et-cert.pem
    OrganizationalUnitIdentifier: orderer
