#!/usr/bin/env bash
# Ethiopian Coffee Export Consortium Blockchain System (CECBS)
# Full Installation & Setup Script
#
# Usage: bash install.sh [OPTIONS]
#
# Options:
#   --prod              Generate production-strength secrets
#   --skip-blockchain   Skip Fabric network setup entirely (API+UI only)
#   --no-start          Generate configs & install deps, but don't start Docker containers
#   --upgrade           Upgrade chaincode to next sequence number

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$SCRIPT_DIR/api"
UI_DIR="$SCRIPT_DIR/ui"
BLOCKCHAIN_DIR="$SCRIPT_DIR/blockchain"
SCRIPTS_DIR="$SCRIPT_DIR/scripts"

PROD=false
SKIP_BLOCKCHAIN=false
NO_START=false
UPGRADE=false

for arg in "$@"; do
  case "$arg" in
    --prod)             PROD=true ;;
    --skip-blockchain)  SKIP_BLOCKCHAIN=true ;;
    --no-start)         NO_START=true ;;
    --upgrade)          UPGRADE=true ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

require_cmd() { command -v "$1" >/dev/null 2>&1 || error "$1 not found. $2"; }

gen_secret() {
  local len="${1:-64}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$len"
  elif [ -r /dev/urandom ]; then
    head -c "$len" /dev/urandom | od -A n -t x1 | tr -d ' \n' | head -c $((len * 2))
  else
    echo "cecbs-$(date +%s)"
  fi
}

write_env_if_missing() {
  local dest="$1"; local content="$2"
  if [ -f "$dest" ]; then
    warn "$dest already exists — skipping (delete to regenerate)"
  else
    printf '%s\n' "$content" > "$dest"
    success "Created $dest"
  fi
}

wait_for_container() {
  local name="$1"; local retries="${2:-30}"
  info "Waiting for container $name to be healthy..."
  for i in $(seq 1 "$retries"); do
    if docker inspect --format='{{.State.Running}}' "$name" 2>/dev/null | grep -q true; then
      success "$name is running"
      return 0
    fi
    sleep 2
  done
  error "Container $name did not start in time"
}

echo ""
echo -e "${CYAN}════════════════════════════════════════════${NC}"
echo -e "${CYAN}  CECBS — Full Blockchain System Setup${NC}"
echo -e "${CYAN}════════════════════════════════════════════${NC}"
echo ""

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
info "[1] Checking prerequisites..."
require_cmd node  "Install Node.js 18+  https://nodejs.org"
require_cmd npm   "Install Node.js 18+  https://nodejs.org"
NODE_MAJOR=$(node -e "process.stdout.write(process.versions.node.split('.')[0])")
[ "$NODE_MAJOR" -ge 18 ] || error "Node.js 18+ required (found $(node --version))"

if ! $SKIP_BLOCKCHAIN; then
  require_cmd docker "Install Docker Desktop https://www.docker.com/products/docker-desktop"
  docker info >/dev/null 2>&1 || error "Docker daemon is not running. Start Docker Desktop and try again."
fi
success "Prerequisites OK"

# ── Step 2: Environment Files ─────────────────────────────────────────────────
info "[2] Generating environment files..."

if $PROD; then
  JWT_SECRET="$(gen_secret 64)"
  SESSION_SECRET="$(gen_secret 64)"
  NODE_ENV="production"
  FABRIC_ENABLED="true"
  FABRIC_AS_LOCALHOST="false"
else
  JWT_SECRET="cecbs-dev-jwt-secret-change-in-production"
  SESSION_SECRET="cecbs-dev-session-secret-change-in-production"
  NODE_ENV="development"
  # Will be set to true after blockchain is confirmed running
  FABRIC_ENABLED="false"
  FABRIC_AS_LOCALHOST="true"
fi

write_env_if_missing "$API_DIR/.env" \
"# CECBS API Gateway — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=${NODE_ENV}
PORT=3001
API_BASE_URL=http://localhost:3001/api/v1

# CORS
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=24h

# Session
SESSION_SECRET=${SESSION_SECRET}
BCRYPT_ROUNDS=10

# Hyperledger Fabric
# Set FABRIC_ENABLED=true once the blockchain network is running.
# Set FABRIC_AS_LOCALHOST=false when running inside Docker.
FABRIC_ENABLED=${FABRIC_ENABLED}
FABRIC_REQUIRED=false
FABRIC_AS_LOCALHOST=${FABRIC_AS_LOCALHOST}
FABRIC_WALLET_PATH=./wallet
FABRIC_CCP_PATH=../blockchain/organizations/peerOrganizations/ecta.cecbs.et/connection-ecta.json
FABRIC_CHANNEL_NAME=coffeechannel
FABRIC_CHAINCODE_NAME=coffee
FABRIC_MSP_ID=ECTAMSP
FABRIC_CA_URL=https://localhost:7054

# Database
DATABASE_PATH=./cecbs.db

# Logging
LOG_LEVEL=info
LOG_DIR=./logs

# File Uploads
UPLOAD_DIR=./uploads
MAX_FILE_SIZE=10485760

# WebSocket
WS_PORT=3002

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=1000
BLOCKCHAIN_RATE_LIMIT_MAX=100

# Feature Flags
ENABLE_SWAGGER=true
ENABLE_WEBSOCKET=true
ENABLE_FILE_UPLOAD=true
"

write_env_if_missing "$UI_DIR/.env.local" \
"# CECBS Next.js UI — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NEXT_PUBLIC_API_BASE_URL=http://localhost:3001/api/v1
NEXT_PUBLIC_WS_URL=ws://localhost:3002
CECBS_API_URL=http://localhost:3001/api/v1
NEXT_PUBLIC_APP_NAME=CECBS
NEXT_PUBLIC_APP_VERSION=1.2.0
NEXT_PUBLIC_APP_DESCRIPTION=Ethiopian Coffee Export Consortium Blockchain System
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ENABLE_WEBSOCKET=true
NEXT_PUBLIC_ENABLE_QR_CODE=true
NEXT_PUBLIC_DEFAULT_ORG=ECTA
NEXT_PUBLIC_SUPPORTED_ORGS=ECTA,ECX,NBE,BANKS,CUSTOMS,SHIPPING
NEXT_PUBLIC_MAPBOX_TOKEN=
NEXT_PUBLIC_DEFAULT_MAP_CENTER_LAT=9.0320
NEXT_PUBLIC_DEFAULT_MAP_CENTER_LNG=38.7469
NEXT_PUBLIC_GA_TRACKING_ID=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_DEFAULT_LOCALE=en
NEXT_PUBLIC_SUPPORTED_LOCALES=en,am
"

# ── Step 3: Install Node.js dependencies ─────────────────────────────────────
info "[3] Installing API dependencies..."
(cd "$API_DIR" && npm install --prefer-offline 2>&1 | tail -3)
success "API dependencies installed"

info "[4] Installing UI dependencies..."
(cd "$UI_DIR" && npm install --prefer-offline 2>&1 | tail -3)
success "UI dependencies installed"

# ── Blockchain setup ──────────────────────────────────────────────────────────
if $SKIP_BLOCKCHAIN; then
  warn "Skipping blockchain setup (--skip-blockchain)"
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Setup complete (no blockchain)${NC}"
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo ""
  echo "  Start API:  cd api && npm run dev"
  echo "  Start UI:   cd ui && npm run dev"
  echo "  Open:       http://localhost:3000"
  echo ""
  exit 0
fi

# ── Step 5: Crypto materials ──────────────────────────────────────────────────
info "[5] Generating Fabric crypto materials..."
if [ -d "$BLOCKCHAIN_DIR/organizations/peerOrganizations/ecta.cecbs.et" ]; then
  warn "Crypto materials already exist — skipping (delete blockchain/organizations to regenerate)"
else
  export MSYS_NO_PATHCONV=1
  docker run --rm \
    -v "${SCRIPT_DIR}://work" \
    -w //work \
    hyperledger/fabric-tools:2.5 \
    cryptogen generate \
      --config=blockchain/crypto-config.yaml \
      --output=blockchain/organizations
  success "Crypto materials generated"
fi

# ── Step 6: Channel artifacts ─────────────────────────────────────────────────
info "[6] Generating channel artifacts..."
ARTIFACTS_DIR="$BLOCKCHAIN_DIR/channel-artifacts"
mkdir -p "$ARTIFACTS_DIR"

if [ -f "$ARTIFACTS_DIR/genesis.block" ] && [ -f "$ARTIFACTS_DIR/coffeechannel.tx" ]; then
  warn "Channel artifacts already exist — skipping"
else
  export MSYS_NO_PATHCONV=1

  info "  Generating genesis block..."
  docker run --rm \
    -v "${SCRIPT_DIR}://work" \
    -w //work \
    hyperledger/fabric-tools:2.5 \
    configtxgen \
      -profile CoffeeOrdererGenesis \
      -channelID system-channel \
      -outputBlock blockchain/channel-artifacts/genesis.block \
      -configPath blockchain

  info "  Generating channel creation transaction..."
  docker run --rm \
    -v "${SCRIPT_DIR}://work" \
    -w //work \
    hyperledger/fabric-tools:2.5 \
    configtxgen \
      -profile CoffeeChannel \
      -outputCreateChannelTx blockchain/channel-artifacts/coffeechannel.tx \
      -channelID coffeechannel \
      -configPath blockchain

  info "  Generating anchor peer transactions..."
  for ORG in ECTA ECX Banks NBE Customs Shipping; do
    docker run --rm \
      -v "${SCRIPT_DIR}://work" \
      -w //work \
      hyperledger/fabric-tools:2.5 \
      configtxgen \
        -profile CoffeeChannel \
        -outputAnchorPeersUpdate "blockchain/channel-artifacts/${ORG}MSPanchors.tx" \
        -channelID coffeechannel \
        -asOrg "${ORG}MSP" \
        -configPath blockchain
  done

  success "Channel artifacts generated"
fi

if $NO_START; then
  warn "--no-start: skipping container startup and channel/chaincode setup"
  echo ""
  echo "Artifacts ready. To start the network:"
  echo "  docker-compose -f docker-compose-fabric.yml up -d"
  echo "  bash scripts/create-channel-docker.sh"
  echo "  bash scripts/join-peers-to-channel.sh"
  echo "  bash scripts/deploy-chaincode.sh"
  exit 0
fi

# ── Step 7: Start Fabric network ──────────────────────────────────────────────
info "[7] Starting Fabric network..."

# Bring down any existing deployment cleanly
docker compose -f "$SCRIPT_DIR/docker-compose-fabric.yml" down --remove-orphans 2>/dev/null || \
  docker-compose -f "$SCRIPT_DIR/docker-compose-fabric.yml" down --remove-orphans 2>/dev/null || true

docker compose -f "$SCRIPT_DIR/docker-compose-fabric.yml" up -d 2>/dev/null || \
  docker-compose -f "$SCRIPT_DIR/docker-compose-fabric.yml" up -d

success "Fabric containers started"

# ── Step 8: Wait for peers ────────────────────────────────────────────────────
info "[8] Waiting for orderer and peers to be ready (30s)..."
sleep 30
wait_for_container "orderer.cecbs.et"
wait_for_container "peer0.ecta.cecbs.et"
wait_for_container "peer0.ecx.cecbs.et"
wait_for_container "peer0.banks.cecbs.et"
wait_for_container "peer0.nbe.cecbs.et"
wait_for_container "peer0.customs.cecbs.et"
wait_for_container "peer0.shipping.cecbs.et"
wait_for_container "coffee-chaincode"

# ── Step 9: Create channel and join peers ─────────────────────────────────────
info "[9] Creating channel and joining all peers..."
bash "$SCRIPTS_DIR/create-channel-docker.sh"
bash "$SCRIPTS_DIR/join-peers-to-channel.sh"

# ── Step 10: Deploy chaincode ─────────────────────────────────────────────────
if $UPGRADE; then
  info "[10] Upgrading chaincode..."
  # Determine next sequence from current committed sequence
  CURRENT_SEQ=$(docker run --rm \
    --network cecbs-network \
    -v "${SCRIPT_DIR}:/work" \
    -e CORE_PEER_TLS_ENABLED=true \
    -e CORE_PEER_LOCALMSPID=ECTAMSP \
    -e CORE_PEER_TLS_ROOTCERT_FILE=/work/blockchain/organizations/peerOrganizations/ecta.cecbs.et/peers/peer0.ecta.cecbs.et/tls/ca.crt \
    -e CORE_PEER_MSPCONFIGPATH=/work/blockchain/organizations/peerOrganizations/ecta.cecbs.et/users/Admin@ecta.cecbs.et/msp \
    -e CORE_PEER_ADDRESS=peer0.ecta.cecbs.et:7051 \
    hyperledger/fabric-tools:2.5 \
    peer lifecycle chaincode querycommitted \
      --channelID coffeechannel --name coffee --output json 2>/dev/null \
    | grep -o '"sequence":[0-9]*' | grep -o '[0-9]*' || echo "0")
  NEXT_SEQ=$((CURRENT_SEQ + 1))
  NEW_VERSION="1.$((11 + NEXT_SEQ - 1))"
  info "Upgrading from sequence $CURRENT_SEQ to $NEXT_SEQ, version $NEW_VERSION"
  bash "$SCRIPTS_DIR/deploy-chaincode.sh" "$NEW_VERSION"
else
  info "[10] Deploying chaincode..."
  bash "$SCRIPTS_DIR/deploy-chaincode.sh"
fi

# ── Step 11: Enable Fabric in API env ─────────────────────────────────────────
info "[11] Enabling Fabric connectivity in api/.env..."
if grep -q "FABRIC_ENABLED=false" "$API_DIR/.env"; then
  # Use sed to flip the flag
  sed -i 's/FABRIC_ENABLED=false/FABRIC_ENABLED=true/' "$API_DIR/.env"
  success "FABRIC_ENABLED set to true in api/.env"
else
  warn "FABRIC_ENABLED was already true or not found — check api/.env manually"
fi

echo ""
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  CECBS Blockchain System Ready!${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo ""
echo "  Blockchain: Running (all peers on coffeechannel)"
echo "  Chaincode:  coffee (CaaS on coffee-chaincode:9999)"
echo ""
echo "  Start API:  cd api && npm run dev"
echo "  Start UI:   cd ui && npm run dev"
echo "  Open:       http://localhost:3000"
echo ""
echo "Useful commands:"
echo "  Network logs:   docker-compose -f docker-compose-fabric.yml logs -f"
echo "  Chaincode logs: docker logs -f coffee-chaincode"
echo "  Stop network:   docker-compose -f docker-compose-fabric.yml down"
echo ""
