# Ethiopian Coffee Export Consortium Blockchain System (CECBS)
# Full Installation & Setup Script for Windows (PowerShell)
#
# Usage: .\install.ps1 [-Prod] [-SkipBlockchain] [-NoStart] [-Upgrade]
#
# Options:
#   -Prod             Generate production-strength secrets
#   -SkipBlockchain   Skip Fabric network setup (API+UI only)
#   -NoStart          Generate configs & install deps but don't start Docker
#   -Upgrade          Upgrade chaincode to next sequence number

param(
  [switch]$Prod,
  [switch]$SkipBlockchain,
  [switch]$NoStart,
  [switch]$Upgrade
)

$ErrorActionPreference = 'Stop'

$RepoRoot       = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$ApiPath        = Join-Path $RepoRoot 'api'
$UiPath         = Join-Path $RepoRoot 'ui'
$ChaincodePath  = Join-Path $RepoRoot 'chaincodes\coffee'
$BlockchainPath = Join-Path $RepoRoot 'blockchain'

# ── Helpers ───────────────────────────────────────────────────────────────────
function Require-Command([string]$Name, [string]$Hint) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: $Name not found. $Hint" -ForegroundColor Red
    exit 1
  }
}

function Gen-Secret([int]$Bytes = 64) {
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $data = New-Object byte[] $Bytes
  $rng.GetBytes($data)
  return ([System.BitConverter]::ToString($data) -replace '-','').ToLower()
}

function Write-EnvIfMissing([string]$Path, [string]$Content) {
  if (Test-Path $Path) {
    Write-Host "WARN:  $Path already exists — skipping (delete it to regenerate)" -ForegroundColor Yellow
  } else {
    Set-Content -Path $Path -Value $Content -Encoding UTF8
    Write-Host "OK:    Created $Path" -ForegroundColor Green
  }
}

Write-Host ''
Write-Host '════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host '  CECBS Installation' -ForegroundColor Cyan
Write-Host '════════════════════════════════════════════' -ForegroundColor Cyan
Write-Host ''

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
Write-Host '[1/8] Checking prerequisites...' -ForegroundColor Yellow
Require-Command 'node' 'Install Node.js 18+ from https://nodejs.org'
Require-Command 'npm'  'Install Node.js 18+ from https://nodejs.org'

$NodeMajor = [int](node -e "process.stdout.write(process.versions.node.split('.')[0])")
if ($NodeMajor -lt 18) {
  Write-Host "ERROR: Node.js 18+ required (found $(node --version))" -ForegroundColor Red
  exit 1
}

if (-not $SkipBlockchain) {
  Require-Command 'docker' 'Install Docker Desktop from https://www.docker.com/products/docker-desktop'
  Require-Command 'go'     'Install Go 1.21+ from https://go.dev/dl/'
}
Write-Host "OK:    Prerequisites OK (node $(node --version))" -ForegroundColor Green

# ── Step 2: API .env ──────────────────────────────────────────────────────────
Write-Host '[2/8] Generating API environment file...' -ForegroundColor Yellow

$Timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

if ($Prod) {
  $JwtSecret     = Gen-Secret 64
  $SessionSecret = Gen-Secret 64
  $NodeEnv       = 'production'
  $FabricEnabled = 'true'
  $FabricAsLocalhost = 'false'
  $FabricRequired = 'false'
} else {
  $JwtSecret     = 'cecbs-dev-jwt-secret-change-in-production'
  $SessionSecret = 'cecbs-dev-session-secret-change-in-production'
  $NodeEnv       = 'development'
  $FabricEnabled = 'false'
  $FabricAsLocalhost = 'true'
  $FabricRequired = 'false'
}

$ApiEnv = @"
# Ethiopian Coffee Export Consortium Blockchain System (CECBS)
# API Gateway — generated by install.ps1 on $Timestamp
# Re-run install.ps1 or edit this file to change settings.

# ── Server ────────────────────────────────────────────────────────────────────
NODE_ENV=$NodeEnv
PORT=3001
API_BASE_URL=http://localhost:3001/api/v1

# ── CORS ──────────────────────────────────────────────────────────────────────
# Comma-separated list of allowed frontend origins
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001

# ── JWT Authentication ────────────────────────────────────────────────────────
JWT_SECRET=$JwtSecret
JWT_EXPIRY=24h

# ── Session ───────────────────────────────────────────────────────────────────
SESSION_SECRET=$SessionSecret
BCRYPT_ROUNDS=10

# ── Hyperledger Fabric ────────────────────────────────────────────────────────
# Set FABRIC_ENABLED=true once the blockchain network is running.
# Set FABRIC_AS_LOCALHOST=false when running inside Docker.
FABRIC_ENABLED=$FabricEnabled
FABRIC_REQUIRED=$FabricRequired
FABRIC_AS_LOCALHOST=$FabricAsLocalhost
FABRIC_WALLET_PATH=./wallet
FABRIC_CCP_PATH=../blockchain/organizations/peerOrganizations/ecta.cecbs.et/connection-ecta.json
FABRIC_CHANNEL_NAME=coffeechannel
FABRIC_CHAINCODE_NAME=coffee
FABRIC_MSP_ID=ECTAMSP
FABRIC_CA_URL=https://localhost:7054

# ── Database ──────────────────────────────────────────────────────────────────
# Path to the SQLite database file (relative to api/ directory)
DATABASE_PATH=./cecbs.db

# ── Logging ───────────────────────────────────────────────────────────────────
LOG_LEVEL=info
LOG_DIR=./logs

# ── File Uploads ──────────────────────────────────────────────────────────────
UPLOAD_DIR=./uploads
MAX_FILE_SIZE=10485760

# ── WebSocket ────────────────────────────────────────────────────────────────
WS_PORT=3002

# ── Rate Limiting ─────────────────────────────────────────────────────────────
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=1000
BLOCKCHAIN_RATE_LIMIT_MAX=100

# ── Feature Flags ────────────────────────────────────────────────────────────
ENABLE_SWAGGER=true
ENABLE_WEBSOCKET=true
ENABLE_FILE_UPLOAD=true
"@

Write-EnvIfMissing (Join-Path $ApiPath '.env') $ApiEnv

# ── Step 3: UI .env ───────────────────────────────────────────────────────────
Write-Host '[3/8] Generating UI environment file...' -ForegroundColor Yellow

$UiEnv = @"
# Ethiopian Coffee Export Consortium Blockchain System (CECBS)
# Next.js UI — generated by install.ps1 on $Timestamp
# NEXT_PUBLIC_* variables are embedded at build time and exposed to the browser.

# ── API Connection ────────────────────────────────────────────────────────────
NEXT_PUBLIC_API_BASE_URL=http://localhost:3001/api/v1
NEXT_PUBLIC_WS_URL=ws://localhost:3002

# Legacy API URL key used by ui/src/utils/api.ts
CECBS_API_URL=http://localhost:3001/api/v1

# ── Application ───────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_NAME=CECBS
NEXT_PUBLIC_APP_VERSION=1.2.0
NEXT_PUBLIC_APP_DESCRIPTION=Ethiopian Coffee Export Consortium Blockchain System

# ── Feature Flags ────────────────────────────────────────────────────────────
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ENABLE_WEBSOCKET=true
NEXT_PUBLIC_ENABLE_QR_CODE=true

# ── Organization ─────────────────────────────────────────────────────────────
NEXT_PUBLIC_DEFAULT_ORG=ECTA
NEXT_PUBLIC_SUPPORTED_ORGS=ECTA,ECX,NBE,BANKS,CUSTOMS,SHIPPING

# ── Map (Mapbox — leave blank to disable map features) ───────────────────────
NEXT_PUBLIC_MAPBOX_TOKEN=
NEXT_PUBLIC_DEFAULT_MAP_CENTER_LAT=9.0320
NEXT_PUBLIC_DEFAULT_MAP_CENTER_LNG=38.7469

# ── Analytics / Monitoring (optional) ────────────────────────────────────────
NEXT_PUBLIC_GA_TRACKING_ID=
NEXT_PUBLIC_SENTRY_DSN=

# ── Locale ───────────────────────────────────────────────────────────────────
NEXT_PUBLIC_DEFAULT_LOCALE=en
NEXT_PUBLIC_SUPPORTED_LOCALES=en,am
"@

Write-EnvIfMissing (Join-Path $UiPath '.env.local') $UiEnv

# ── Step 4: Install API dependencies ─────────────────────────────────────────
Write-Host '[4/8] Installing API dependencies...' -ForegroundColor Yellow
Push-Location $ApiPath
try {
  & npm install
  Write-Host 'OK:    API dependencies installed' -ForegroundColor Green
} finally { Pop-Location }

# ── Step 5: Install UI dependencies ──────────────────────────────────────────
Write-Host '[5/8] Installing UI dependencies...' -ForegroundColor Yellow
Push-Location $UiPath
try {
  & npm install
  Write-Host 'OK:    UI dependencies installed' -ForegroundColor Green
} finally { Pop-Location }

# ── Step 6: Blockchain setup (skippable) ─────────────────────────────────────
if ($SkipBlockchain) {
  Write-Host 'WARN:  [6-8/8] Skipping blockchain setup (-SkipBlockchain)' -ForegroundColor Yellow
} else {
  Write-Host '[6/8] Building chaincode...' -ForegroundColor Yellow
  if (Test-Path $ChaincodePath) {
    Push-Location $ChaincodePath
    try {
      & go build ./...
      Write-Host 'OK:    Chaincode built' -ForegroundColor Green
    } finally { Pop-Location }
  } else {
    Write-Host "WARN:  Chaincode directory not found at $ChaincodePath — skipping" -ForegroundColor Yellow
  }

  Write-Host '[7/8] Generating Fabric crypto materials...' -ForegroundColor Yellow
  $OrgDir = Join-Path $BlockchainPath 'organizations\ordererOrganizations'
  if (Test-Path $OrgDir) {
    Write-Host 'WARN:  Crypto materials already exist — skipping' -ForegroundColor Yellow
  } else {
    & docker run --rm `
      -v "${BlockchainPath}:/blockchain" `
      hyperledger/fabric-tools:2.5 `
      cryptogen generate `
        --config=/blockchain/crypto-config.yaml `
        --output=/blockchain/organizations
    Write-Host 'OK:    Crypto materials generated' -ForegroundColor Green
  }

  Write-Host '[8/8] Generating channel artifacts...' -ForegroundColor Yellow
  $ChannelBlock = Join-Path $BlockchainPath 'channel-artifacts\coffeechannel.block'
  if (Test-Path $ChannelBlock) {
    Write-Host 'WARN:  Channel artifacts already exist — skipping' -ForegroundColor Yellow
  } else {
    & docker run --rm `
      -v "${BlockchainPath}:/blockchain" `
      hyperledger/fabric-tools:2.5 `
      configtxgen `
        -profile CoffeeOrdererGenesis `
        -channelID system-channel `
        -outputBlock /blockchain/channel-artifacts/genesis.block `
        -configPath /blockchain

    & docker run --rm `
      -v "${BlockchainPath}:/blockchain" `
      hyperledger/fabric-tools:2.5 `
      configtxgen `
        -profile CoffeeChannel `
        -outputCreateChannelTx /blockchain/channel-artifacts/coffeechannel.tx `
        -channelID coffeechannel `
        -configPath /blockchain
    Write-Host 'OK:    Channel artifacts generated' -ForegroundColor Green
  }
}

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '════════════════════════════════════════════' -ForegroundColor Green
Write-Host '  Installation complete!' -ForegroundColor Green
Write-Host '════════════════════════════════════════════' -ForegroundColor Green
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host "  Start API:  cd api; npm run dev"
Write-Host "  Start UI:   cd ui; npm run dev"
Write-Host '  Open:       http://localhost:3000'
Write-Host ''

if (-not $SkipBlockchain) {
  Write-Host 'To enable blockchain connectivity:' -ForegroundColor Yellow
  Write-Host '  1. Start the Fabric network (docker-compose)'
  Write-Host '  2. Set FABRIC_ENABLED=true in api\.env'
  Write-Host '  3. Restart the API'
  Write-Host ''
}

if ($Prod) {
  Write-Host 'Production secrets were generated.' -ForegroundColor Yellow
  Write-Host '  Review api\.env and keep it out of version control.'
  Write-Host ''
}
